<?xml version="1.0"?>
<package format="3">
  <name>duckiebot_description</name>
  <version>0.1.0</version>
  <description>Duckiebot description assets and ROS 2 launch files.</description>
  <maintainer email="leensaid24@gmail.com">Leen Said</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>xacro</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
