%YAML:1.0

#common parameters
imu_topic: "/imu_data"
image_topic: "/duckiebot/camera1/image_raw"
output_path: "/home/mnt/ws/src/VINS-Mono/output/"

model_type: PINHOLE
camera_name: camera
image_width: 320
image_height: 240

# Camera Calibration
distortion_parameters:
   k1: 0.0
   k2: 0.0
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: 279.446
   fy: 279.446
   cx: 160.0
   cy: 120.0

# Extrinsics (Camera to IMU)
estimate_extrinsic: 0
body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0, 0, 1, 0, -1, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 1]

# IMU Parameters
acc_n: 0.1
gyr_n: 0.01
acc_w: 0.0002
gyr_w: 2.0e-5
g_norm: 9.81007
td: 0.0